<a href="https://colab.research.google.com/github/kyuwan25/26/blob/main/26_07_12_%EB%8F%99%EC%B0%A8%ED%96%89%EB%A0%AC%EB%93%A4%EC%9D%98_%EA%B3%B1%EC%85%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#다관절로봇팔에서 dh_table을 통해 end-effector의 위치와 각도를 알 수 있는 코드를 만들었다.
import numpy as np

def DH(a,alpha,d,theta):
  ap,t = np.deg2rad(alpha), np.deg2rad(theta)
  c,s = np.cos(t),np.sin(t)
  ca,sa = np.cos(ap),np.sin(ap)
  T = np.array([[c,-s,0,a],
                  [s*ca,c*ca,-sa,-sa*d],
                  [s*sa,c*sa,ca,ca*d],
                  [0,0,0,1]])
  return T
print("i=1일때 입니다.")
a0 = float(input("a'0' : "))
alpha0 = float(input("alpha'0' : "))
d1 = float(input("d'1' : "))
theta1 = float(input("theta'1' : "))
print("i=2일때 입니다.")
a1 = float(input("a'1' : "))
alpha1 = float(input("alpha'1' : "))
d2 = float(input("d'2' : "))
theta2 = float(input("theta'2' : "))
print("i=3일때 입니다.")
a2 = float(input("a'2' : "))
alpha2 = float(input("alpha'2' : "))
d3 = float(input("d'3' : "))
theta3 = float(input("theta'3' : "))

#클로드의 조언을 바탕으로 for문을 통해서 곱셈을 구현하였다.
dh_table = [(a0,alpha0,d1,theta1),
             (a1,alpha1,d2,theta2),
             (a2,alpha2,d3,theta3)]

T_total = np.eye(4)
for params in dh_table:
    Ti = DH(*params)
    T_total = T_total @ Ti
T_result = np.round(T_total,4)
print("end-effector의 위치")
print(T_result[0:3,3])
print("end-effector의 자세")
print(T_result[0:3,0:3])

i=1일때 입니다.
a'0' : 0
alpha'0' : 0
d'1' : 0
theta'1' : 90
i=2일때 입니다.
a'1' : 0
alpha'1' : 90
d'2' : 0
theta'2' : 90
i=3일때 입니다.
a'2' : 0
alpha'2' : 90
d'3' : 0
theta'3' : 90
end-effector의 위치
[0. 0. 0.]
end-effector의 자세
[[ 1.  0.  0.]
 [-0. -0.  1.]
 [ 0. -1. -0.]]
